### ISSUE TITLE
[WARNING] Container parameters not found, skipping parameters modification

### ISSUE THREAD

**Issue by ho0p3r** [fuzziebrain/docker-apex-stack#1]
Hi Adrian,
i got this message at 2nd step after downloading dependencies inside docker container:
[WARNING] Container parameters not found, skipping parameters modification
Ima running Ubuntu 18.04.2 LTS and Docker CE version 18.09.3 at my old HP Envy laptop with 6gb RAM:)
~/repo/docker-apex-stack$ ./02-build.sh starterkit.env 
[stage2.log](https://github.com/fuzziebrain/docker-apex-stack/files/2927654/stage2.log)
starterkit.env:
ORACLE_SID=starterkit
ORACLE_PDB=xe1
ORACLE_PWD=Oracle_18XE#pass
APEX_ADMIN_EMAIL=***@***.com
APEX_ADMIN_PWD=Oracle18XE#pass
INSTALL_FILE_APEX=apex_18.2_en.zip
INSTALL_FILE_ORDS=ords-18.4.0.354.1002.zip
DOCKER_ORDS_PORT=50080
DOCKER_EM_PORT=55500
DOCKER_DB_PORT=51521
DB_VERSION=18.4.0
DB_EDITION=XE

**Comment by ho0p3r** [comment]
full stage2 and stage3
[stage2.log](https://github.com/fuzziebrain/docker-apex-stack/files/2927847/stage2.log)
[stage3.log](https://github.com/fuzziebrain/docker-apex-stack/files/2927848/stage3.log)

**Comment by fuzziebrain** [comment]
@ho0p3r I had some fixes that might resolve this issue. Can you please try again and let me know? Thanks!

**Comment by fuzziebrain** [comment]
Closing this. Please reopen if it's still an issue.
