### ISSUE TITLE
problem with ords on mac osx

### ISSUE THREAD

**Issue by carldewever** [fuzziebrain/docker-apex-stack#13]
everything goes fine until the error where apparently java is not found in the runords.sh script...
any ideas?

#########################
DATABASE IS READY TO USE!
#########################

Executing user defined scripts
/opt/oracle/runOracle.sh: running /opt/oracle/scripts/startup/01-run.sh
##### Starting ORDS #####
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/scripts/startup/package/runOrds.sh: line 15: java: command not found
/opt/oracle/scripts/startup/package/runOrds.sh: line 17: java: command not found

/opt/oracle/runOracle.sh: ignoring /opt/oracle/scripts/startup/package

**Comment by fuzziebrain** [comment]
@carldewever 

Just to be sure:
1. Have you downloaded the JDK8 and placed it in the files directory?
2. Have you pulled the latest changes in this repository?

Thanks.

**Comment by carldewever** [comment]
I have jdk-8u211-linux-x64.rpm in my files directory. 
I also refer to this file in my settings file :
INSTALL_FILE_APEX=apex_19.1.zip
INSTALL_FILE_ORDS=ords-19.1.0.092.1545.zip
INSTALL_FILE_JAVA=jdk-8u211-linux-x64.rpm

I started with a clean directory without any "dockerfiles" directory at all

**Comment by fuzziebrain** [comment]
I guess I did not make it clear enough to download the tarball. I'll make some changes. Thanks.
