### ISSUE TITLE
ORDS Not running

### ISSUE THREAD

**Issue by cruepprich** [fuzziebrain/docker-apex-stack#14]
Adrian,
i ran the installation on Oracle Linx Server 7.6 on an OCI compute instance, without apparent errors.
I'm able to log into the XE database from the host:
$ sqlcl system/xxx@localhost:51521/xepdb1

Trying curl to check ORDS, I get the following:
curl localhost:50080/ords/
curl: (56) Recv failure: Connection reset by peer

I logged into the container and tried:
bash-4.2# curl -I http://localhost:8080/ords
curl: (7) Failed to connect to ::1: Cannot assign requested address

I checked ps and didn't see ORDS running. Not any Java either.

I checked the contents of the directory /opt/oracle/product/ords and saw no config directory.

Somehow the ORDS configuration must have been skipped. Any suggestions?
Thx

**Comment by fuzziebrain** [comment]
Hi Christoph,

Did you download and place the JDK in the files directory? You'll need the tarball and not the RPM. I will be updating the documentation to make it clearer what is needed.

**Comment by cruepprich** [comment]
Hi Adrian,
i just checked my files directory and it's not there. Will jdk-12.0.1_linux-x64_bin.rpm work?

**Comment by fuzziebrain** [comment]
@cruepprich Nope. Get the .tar.gz file instead. And please download JDK8.

**Comment by cruepprich** [comment]
Ok. Should i blow away the current container and run 01-build.sh again?

**Comment by fuzziebrain** [comment]
Probably not. The tarball is only needed when running a container. The 02-run.sh script will also take care of removing any containers with the same name. You might want to remove the "oradata" folder on the host system though, and you might need sudo rights depending on the ownership of that directory.
