### ISSUE TITLE
Support APEX 20.1 and JDK 8u251

### ISSUE THREAD

**Issue by fuzziebrain** [fuzziebrain/docker-apex-stack#24]

**Comment by robertsondas** [comment]
Hi Fuzziebrain
I followed your steps in https://github.com/fuzziebrain/docker-apex-stack

but below error i am getting

Unknown or unsupported database version and/or edition.
 #####Building Docker Image for Oracle Database 18.4.0
Checking Docker version.
 does not have Express Edition available.
