### ISSUE TITLE
Unable to build in dockerhub i says Dockerfile not found

### ISSUE THREAD

**Issue by alifarooq1991** [fuzziebrain/docker-apex-stack#26]
Please add image to docker hub aswell

**Comment by fuzziebrain** [comment]
We do not have the rights to redistribute the software installed, so no, I won't be able to put this image in Docker Hub.

**Comment by alifarooq1991** [comment]
What about Dockerfile?

**Comment by fuzziebrain** [comment]
> What about Dockerfile?

Please follow the instructions in the README.md on how to use these scripts. Thanks.
