### ISSUE TITLE
Unable to install APEX

### ISSUE THREAD

**Issue by fuzziebrain** [fuzziebrain/docker-apex-stack#27]
Hi @fuzziebrain, thank you for quick response. After providing necessary permisson to my das-oradata folder prior to running the docker (2nd step), I was able to get past DB installation and my database is up and running. Thank you so much. 

However, I had encountered a minor issue while installing the Apex. Kindly refer the highlighted/bold section. Shell unable to extract or find the apex_20_1.zip file, even though I had placed those in my files directory prior to running the script. Do I need to grant full permission there as well? Please suggest. 

Thank you so much for your work, its really helps. If you have Buy me coffee link, please let me know, I am happy support. 

Regards,
Karthikeyan

Log:
100% complete
Database creation complete. For details check the logfiles at:
 /opt/oracle/cfgtoollogs/dbca/XE.
Database Information:
Global Database Name:XE
System Identifier(SID):XE
Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.

Connect to Oracle Database using one of the connect strings:
     Pluggable database: 27744138d70f/XEPDB1
     Multitenant container database: 27744138d70f
Use https://localhost:5500/em to access Oracle Enterprise Manager for Oracle Database XE

Executing user defined scripts
/opt/oracle/runOracle.sh: running /opt/oracle/scripts/setup/01-install.sh
##### Extracting files ####
**unzip:  cannot find or open /tmp/files/apex_20.1.zip, /tmp/files/apex_20.1.zip.zip or /tmp/files/apex_20.1.zip.ZIP.
chown: cannot access '/opt/oracle/product/apex': No such file or directory**
##### Installing APEX #####
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/scripts/setup/package/installApex.sh: line 10: cd: /opt/oracle/product/apex: No such file or directory
Installing APEX

SQL*Plus: Release 18.0.0.0.0 - Production on Sun Jun 21 21:02:49 2020
Version 18.4.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

Connected to:
Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0

SQL> 
Session altered.

SQL> SQL> SQL> SP2-0310: unable to open file "apexins.sql"
SQL> SQL> SQL> SP2-0310: unable to open file "apex_rest_config_core.sql"
SQL> SQL> SQL>   alter user apex_public_user identified by "Oracle18_1" account unlock
             *
ERROR at line 1:
ORA-01918: user 'APEX_PUBLIC_USER' does not exist

SQL> SQL> SQL> Setup Network ACL
SQL>   2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18  
PL/SQL procedure successfully completed.

SQL> SQL> SQL> Setup APEX Admin account
SQL>   2    3    4    5    6    7    8    9   10   11   12      apex_util.set_workspace(p_workspace => 'internal');
    *
ERROR at line 2:
ORA-06550: line 2, column 5:
PLS-00201: identifier 'APEX_UTIL.SET_WORKSPACE' must be declared
ORA-06550: line 2, column 5:
PL/SQL: Statement ignored
ORA-06550: line 3, column 5:
PLS-00201: identifier 'APEX_UTIL.CREATE_USER' must be declared
ORA-06550: line 3, column 5:
PL/SQL: Statement ignored

SQL> Disconnected from Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0
##### Installing ORDS #####

_Originally posted by @kridhick in https://github.com/fuzziebrain/docker-apex-stack/issues/8#issuecomment-647187660_

**Comment by fuzziebrain** [comment]
@kridhick 

Thanks for your kind thought. Paying forward would be more than sufficient.

If you don't mind, I'll open this as a new issue for discussion. Are you able to provide me a copy of `mysettings.env` after removing any passwords?

**Comment by kridhick** [comment]
ORACLE_SID=XE
ORACLE_PDB=XEPDB1
ORACLE_PWD=Log123456
APEX_ADMIN_EMAIL=rskarthikeyan@protonmail.com
APEX_ADMIN_PWD=Log123456
APEX_PUBLIC_USER_PWD=Log123456
APEX_LISTENER_PWD=Log123456
APEX_REST_PUBLIC_USER_PWD=Log123456
ORDS_PUBLIC_USER_PWD=Log123456
INSTALL_FILE_APEX=apex_20.1.zip
INSTALL_FILE_ORDS=ords-19.2.0.199.1647.zip
INSTALL_FILE_JAVA=jdk-14.0.1_linux-x64_bin.tar.gz
DOCKER_ORDS_PORT=50080
DOCKER_EM_PORT=55500
DOCKER_DB_PORT=51521
DB_VERSION=18.4.0
DB_EDITION=xe
DOCKER_NETWORK_NAME=oracle_network
ALLOW_DB_PATCHING=N
OML4R_SUPPORT=N
REST_ENABLED_SQL=Y
RTU_ENABLED=N
SQLDEVWEB=Y

**Comment by kridhick** [comment]
Hi @fuzziebrain, Kindly close this question. There is a mistake on my end. I had download the english only version of Apex installer which has the apex_20_1_**en**.zip not the apex_20_1.zip. After giving correct name in env file, the program looks good. Apologies for the inconvience it might have caused. Thanks.,

**Comment by fuzziebrain** [comment]
> Hi @fuzziebrain, Kindly close this question. There is a mistake on my end. I had download the english only version of Apex installer which has the apex_20_1_**en**.zip not the apex_20_1.zip. After giving correct name in env file, the program looks good. Apologies for the inconvience it might have caused. Thanks.,

Noted. Thanks for letting me know. Have fun!
