### ISSUE TITLE
Using WSL not working.

### ISSUE THREAD

**Issue by yachtsman60** [fuzziebrain/docker-apex-stack#30]
Please ignore/delete this issue.
The installation files hadn't copied to the docker image correctly and so APEX and ORDS had not been installed at all.
All working now. Thanks

**Comment by fuzziebrain** [comment]
> Please ignore/delete this issue.
> The installation files hadn't copied to the docker image correctly and so APEX and ORDS had not been installed at all.
> All working now. Thanks

OK. Thanks Oliver. Sorry for the late response.
