### ISSUE TITLE
Option to Add Create a Base Oracle Wallet with Standard Root Certs 

### ISSUE THREAD

**Issue by fuzziebrain** [fuzziebrain/docker-apex-stack#4]
This would allow access to Web Services over TLS/SSL. See https://fuzziebrain.com/content/id/1725/

**Comment by martindsouza** [comment]
Sample I used:

```
sh -c "$(curl -fsSL https://gist.githubusercontent.com/fuzziebrain/202f902d8fc6d8de586da5097a501047/raw/fd8930435d3e33ff5cb66ea07e5fd70f031c08e9/createBaseWallet.sh)"

Bundle File: /etc/pki/tls/cert.pem
Wallet Path: /home/oracle/wallets/https_wallet
Wallet Pass: Oradoc_db1
```

To make thing more consistent I'd get the Google pem as part of the script: `curl -O https://pki.goog/roots.pem` and don't prompt for anything.

**Comment by fuzziebrain** [comment]
@martindsouza Thanks for the suggestion and code. This is done (see #6).
