### ISSUE TITLE
Automatically download latest ORDS and APEX files

### ISSUE THREAD

**Issue by yachtsman60** [fuzziebrain/docker-apex-stack#48]
Hi, as a suggested enhancement, rather than having to download and place files in the Files folder, could the scripts be amended to provide the option to simply use the new download links for these elements that no longer need licence acceptance.
ORDS: https://download.oracle.com/otn_software/java/ords/ords-latest.zip
APEX: https://download.oracle.com/otn_software/apex/apex-latest.zip
Many thanks

**Comment by fuzziebrain** [comment]
Hi @yachtsman60,

Thanks for your suggestion. This is similar to what was discussed in #39. I would want to always to give people the opportunity to use a downloaded binary to reduce network traffic. And actually, the `quickstart.sh` actually does download the latest from OTN.

Best regards,
Adrian

**Comment by yachtsman60** [comment]
Hi Adrian,

Thank you for your prompt response and clear answer.
I had taken a look through the scripts to see if I could see it anywhere but missed the new quickstart.sh file.
Brilliant!

All the best
Ollie @ evriINSIGHT in the UK
