### ISSUE TITLE
Unable to find image 'oracle/database:21.3.0-xe'

### ISSUE THREAD

**Issue by chofox** [fuzziebrain/docker-apex-stack#49]
Unable to find image 'oracle/database:21.3.0-xe' locally
docker: Error response from daemon: pull access denied for oracle/database, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

I don't have where to download this file from

**Comment by JoseArostegui** [comment]
Hi! @fuzziebrain 
I'm having the same issue, but don't understand what you mean with "Try running the scripts from here."
(I'm running quickstart.sh in a vagrant box with debian bullseye)
Thanks,
Jose.

**Comment by JoseArostegui** [comment]
```
vagrant@bullseye:~/docker/docker-apex-stack$ more 02-run.log
##### Check if Docker network das_network #####

Error: No such network: das_network
##### Create Docker network das_network #####
b9f6855d6693c8ff1d5d412828179913660f2bed2d989397bd70224b03277cb8
##### Removing any previous containers #####
Error: No such container: apex
##### Changing file ownership. May require password to continue. #####
##### Creating container apex #####
Unable to find image 'oracle/database:21.3.0-xe' locally
docker: Error response from daemon: pull access denied for oracle/database, repository does not exist or may require 'docker login': denied: re
quested access to the resource is denied.
See 'docker run --help'.
##### Tailing logs. Ctrl-C to exit. #####
Error: No such container: apex
vagrant@bullseye:~/docker/docker-apex-stack$
```
("apex" is the name of the container I typed as answer to quickstart.sh)

**Comment by JoseArostegui** [comment]
Hi @chofox , can you please provide guidance?
Thanks,
Jose.
