### ISSUE TITLE
Database install failed

### ISSUE THREAD

**Issue by fmika** [fuzziebrain/docker-apex-stack#5]
Database install fails at the end of 01-build.sh script - oracle user does not have the required privileges ... (see screenshot 
![Snímek obrazovky (99)](https://user-images.githubusercontent.com/15983291/55885626-94c4bc80-5baa-11e9-8f5c-7cb56e2d3007.png))

As recommended, I added variable ORACLE_DOCKER_INSTALL=true to the mysettings.enf file, but without any effect. 

Can you advice?

**Comment by fuzziebrain** [comment]
@fmika You actually do not have to do anything else, but you will need to be able to sudo as root. Can you please let me know more about the environment that you are running this build in?

**Comment by fmika** [comment]
@fuzziebrain   It's OCI environment. I went step by step based on your post https://fuzziebrain.com/content/id/1904/. 
When I faced to the problem with the permissions in 02-run.sh I fixed it based on simple advice at https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/
Later I came to know that the original problem with the permissions is in the first script 01-build.sh

**Comment by fuzziebrain** [comment]
@fmika Ah... actually, for that, I used a modified version of this script:
https://github.com/fuzziebrain/stackscripts/blob/master/lora/deployLora.sh

However, using Docker is also an acceptable approach for a development environment. I take it that you have installed Docker and also using the `opc` account, which has sudo privileges?

**Comment by fmika** [comment]
@fuzziebrain Yes, I have installed all Prerequisities (Git, Curl, Docker) under opc account. I did not set any privileges, I understood these are implicit. Wrong?

**Comment by fuzziebrain** [comment]
@fmika Yes it is. And sorry, I just realised that you had already taken the Docker path. `opc` already has sudo rights and yes, you need to add the user to the `docker` group. When you do, also make sure that you re-login before continuing.

**Comment by fmika** [comment]
@fuzziebrain OK, I will do it morning and give you know.  How should I employ the modified script mentioned above?

**Comment by fuzziebrain** [comment]
@fmika There are quite a few things to do, but I haven't really had the chance to document it. In a nutshell, it involves setting the variables and then modifying it to run on an Oracle Linux system as oppose to one on Centos.

**Comment by fmika** [comment]
@fuzziebrain I added opc user to the docker group, verified that's done correctly (docker:x:992:opc), relogged. Than run 01-build.sh unfortunatelly with the same error.

**Comment by fuzziebrain** [comment]
@fmika Issue looks to be with SELinux. [Change](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security-enhanced_linux/sect-security-enhanced_linux-working_with_selinux-changing_selinux_modes) it to permissive mode until I can figure out a better way to deal with this on OCI.

**Comment by fmika** [comment]
@fuzziebrain OK, changed, just rebooting .. Shall I run 01-build.sh after reboot?

**Comment by fuzziebrain** [comment]
@fmika Yes you should.

**Comment by fmika** [comment]
@fuzziebrain The script did only "Staging RPM". During "Checking if .... valid" the PuTTY window suddenly closed without any error massage.  Tried two times with the same result.

**Comment by fuzziebrain** [comment]
That probably meant that the build failed. Here's what I did to get mine going. This is freshly done.

As *opc* user:

```
$ sudo yum install -y git-core curl docker-engine
$ sudo usermod -aG docker opc
$ sudo systemctl enable docker
```

As *root* user, set SELinux to *persmissive* mode and then reboot.

As *opc* user:

```
$ git clone https://github.com/fuzziebrain/docker-apex-stack.git
$ cd docker-apex-stack/
$ cp settings.env.sample settings.env
```

Change `settings.env` if required, and then upload all four file dependencies to sub-directory `files`.

```
$ . 01-build.sh settings.env
$ . 02-run.sh axer settings.env
```

**Comment by fmika** [comment]
OK, many thanks, I will be back tomorrow.

**Comment by fmika** [comment]
I followed your instructions but result remain unchanged. 
Maybe it would be needed to set SELinux to enforcing on the very beginning, or maybe reinstall ...
After removing and installing git-core curl docker-engine I found that SELinux is keeping permissive mode from previous step. 
Shall I start from beginning with SELinux in enforcing mode and repeat steps once again? What do you mean?

**Comment by fuzziebrain** [comment]
@fmika At least for OEL 7.6, the instance is provisioned with SELinux set to enforcing. That seemed to be causing an issue for me. Turning it off seemed to work. You could try reprovisioning the instance and then try those steps again. Otherwise, I'm not too sure how else I can help you without access to your server.

**Comment by fmika** [comment]
@fuzziebrain OK, I will start from scratch. Thank you for your patience.

**Comment by fuzziebrain** [comment]
@fmika Good luck. Let me know how it goes!

**Comment by fuzziebrain** [comment]
Closing this. Please let me know if you are still having difficulties creating the stack on OCI.
