### ISSUE TITLE
Cannot run 02-run.sh successfully

### ISSUE THREAD

**Issue by sdembele** [fuzziebrain/docker-apex-stack#51]
Hi Adrian, I hope you are well. 
I followed the instructions and it gave me an image **oracle/database:21.3.0-ee**, 
But when I try to execute the command 
**sudo bash 02-run.sh orclapex212 settings.env**
It doesn't end with a success.

My settings 
[settings.txt](https://github.com/fuzziebrain/docker-apex-stack/files/7492156/settings.txt)

And the terminal output
[my_log.txt](https://github.com/fuzziebrain/docker-apex-stack/files/7492154/my_log.txt)

I hope you will find the necessary information here
Thanks

**Comment by fuzziebrain** [comment]
Can you please remove the `orclapex212-oradata` (`sudo rm -rf orclapex212-oradata && sudo -k`) and then try again, this time, without the `sudo` in the run command?
