### ISSUE TITLE
Is it possible to recreate container using existing oradata folder?

### ISSUE THREAD

**Issue by ivars777** [fuzziebrain/docker-apex-stack#58]
During server restore I tried to recreate container with existing oradata folder (mapping oradata to folder of previously existing, but currently deleted container). 02-run.sh finished with "DATABASE SETUP WAS NOT SUCCESSFUL!".  I tried to attach existing dbf files to other XE instance, but it did not work. As a result I have no access to data in the database.
Is it possible somehow to recreate container it it is deleted, but with access to existing oradata folder (particulary dbf files)? Is there any other option how to restore information in dbf files?

**Comment by yacine-zitouni** [comment]
Why would you delete the container ?

**Comment by ivars777** [comment]
There was server problem  and I had to restore it. Normally containers are short living/temporary objects, which are created/recreated as necessary, all persistent information is in persistent storage and container definitions. I could not realize, that this solution does not follow this principle. It it is so, than this is serious drawback and should be noted in description. In this case different backup/restore mechanisms have to be used (e.g. docker commit/save)

**Comment by yacine-zitouni** [comment]
It make sense, can you please tell me how I could have an apex application always up so that after a server restore It will be always here ?

**Comment by fuzziebrain** [comment]
The image is created from Oracle's official Docker images. The data files are stored on the host system file, and you can recreate the container by mapping those files.
