### ISSUE TITLE
 Is Oracle database and APEX need to be installed after container restart ?

### ISSUE THREAD

**Issue by yacine-zitouni** [fuzziebrain/docker-apex-stack#62]
Hello  @fuzziebrain,
I'm pretty new to docker, I'm wondring if all progression will be lost after container restart ( due to server restart for example )

**Comment by yacine-zitouni** [comment]
As I have tested, It seems to be permanent, but I want to confirm that in production it won't be causing any issues,

**Comment by Hichem54B** [comment]
Noo its permanent . Thab dirha en production normal

**Comment by fuzziebrain** [comment]
Again, this is **not** intended to be used in production. The data files are persisted on the host system as per intended by the authors of the official Oracle Docker images.
