### ISSUE TITLE
How to update the APEX in existing container?

### ISSUE THREAD

**Issue by Yah0000** [fuzziebrain/docker-apex-stack#63]
Hi, 
very helpful project. 
I created kontainer when the newest version of APEX was 21.1. In this month Oracle released new ORDS and APEX. 
What is the easiest way to update existing container? 
I know that it is posible to connect to container and manualy update, but I thing that it is posible to use one of existing scripts and re-run setup APEX and ORDS. It is posible?

**Comment by fuzziebrain** [comment]
You can try installing the new version either using a SQL*NET connection to the container's database port, or copy the installation files into the container's file system and run the installation there. Good luck.
