### ISSUE TITLE
download docker APEX can't use

### ISSUE THREAD

**Issue by loho1968** [fuzziebrain/docker-apex-stack#64]
I has down load docker user "docker pull farhansuno/oracle21cxe-server-installed:apex221"
and use this command to run
 "docker run --hostname oracle21cxe-server --name oracle21cxe-server --platform linux/amd64 --privileged=true -d -t -i -p 25:25 -p 80:80 -p 443:443 -p 1521:1521 --memory='4g' --memory-swap='4g' farhansuno/oracle21cxe-server-installed:apex221 /bin/bash -c '/app/setup/restart-services.sh; /bin/bash'"

The apex dont't use, in tomcat log,find this error
    The pool named: |apex1|rt| is invalid and will be ignored: The username or password for the connection pool named |apex1|rt|, are invalid, expired, or the account is locked.
I check database apex1, user not be locked
[apexstart.log](https://github.com/fuzziebrain/docker-apex-stack/files/8812316/apexstart.log)
.

**Comment by fuzziebrain** [comment]
This probably belongs to a different project.
