### ISSUE TITLE
Run fails with "Cannot create directory "/opt/oracle/oradata/XE"."

### ISSUE THREAD

**Issue by riprop** [fuzziebrain/docker-apex-stack#8]
Hi,
running container fails with error below.
Environment: MacOS 10.12.4, Docker Engine 18.09.2, CPU Intel I5 2.6GHz, 8GB RAM

----
sudo su
sh-3.2# . 02-run.sh axer mysettings.env
##### Removing any previous containers #####
axer
##### Creating container axer #####
c557b28728f84ea49ae1d9371a3f4041f02cd7a47eca4e2c4b5cfa217703114f
##### Tailing logs. Ctrl-C to exit. #####
ORACLE PASSWORD FOR SYS AND SYSTEM: Oracle18
Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
Confirm the password:
Configuring Oracle Listener.
Listener configuration succeeded.
Configuring Oracle Database XE.
Enter SYS user password: 
************
Enter SYSTEM user password: 
**********
Enter PDBADMIN User Password: 
********
Prepare for db operation
Cannot create directory "/opt/oracle/oradata/XE".
7% complete
Copying database files
29% complete
100% complete
[FATAL] Recovery Manager failed to restore datafiles. Refer logs for details.
7% complete
0% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.

Database configuration failed. Check logs under '/opt/oracle/cfgtoollogs/dbca'.
mkdir: cannot create directory '/opt/oracle/oradata/dbconfig': Permission denied
mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/spfileXE.ora': No such file or directory
mv: cannot move '/opt/oracle/product/18c/dbhomeXE/dbs/orapwXE' to '/opt/oracle/oradata/dbconfig/XE/': No such file or directory
mv: cannot move '/opt/oracle/product/18c/dbhomeXE/network/admin/listener.ora' to '/opt/oracle/oradata/dbconfig/XE/': No such file or directory
mv: cannot move '/opt/oracle/product/18c/dbhomeXE/network/admin/tnsnames.ora' to '/opt/oracle/oradata/dbconfig/XE/': No such file or directory
cp: cannot create regular file '/opt/oracle/oradata/dbconfig/XE/': No such file or directory
ln: failed to create symbolic link '/opt/oracle/product/18c/dbhomeXE/dbs/orapwXE': File exists
cp: cannot stat '/opt/oracle/oradata/dbconfig/XE/oratab': No such file or directory

**Comment by carldewever** [comment]
I have exactly the same problem
also on mac
os version 10.14.4

**Comment by fuzziebrain** [comment]
@riprop / @carldewever :
There is an instruction in the README:

> The second script requires sudo rights. If your user does not have this privilege, comment out sudo chown 54321:54321 oradata and replace it with chmod 777 oradata.

Can you please do this as a temporary fix? Thanks.

**Comment by carldewever** [comment]
I do have sudo rights but still have this issue

Op za 4 mei 2019 08:01 schreef Adrian Png <notifications@github.com>:

**Comment by fuzziebrain** [comment]
@carldewever Have you tried replacing that line? I have had other Mac users use that fix and it works. I'll be finding a more permanent solution when I can get my hands on one.

**Comment by carldewever** [comment]
chmod 777 oradata did not work.

instead in the finder, I gave myself read/write access to the oradata directory and that worked.

sorry for the delay in the answer.

**Comment by fuzziebrain** [comment]
@carldewever If the first installation failed, you'll need to delete the `oradata` first before attempting a second time. I don't delete the directory automatically for good reason, so you will need to do this manually or the scripts will not create and setup the database again.

**Comment by carldewever** [comment]
The creation of the directory works now, however the installation fails further down the installation process.

Below is a printout of my console window  
Running Custom Scripts
100% complete
Database creation complete. For details check the logfiles at:
 /opt/oracle/cfgtoollogs/dbca/XE.
Database Information:
Global Database Name:XE
System Identifier(SID):XE
Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.

Connect to Oracle Database using one of the connect strings:
     Pluggable database: 8032af6885f3/XEPDB1
     Multitenant container database: 8032af6885f3
Use https://localhost:5500/em to access Oracle Enterprise Manager for Oracle Database XE
mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/spfileORCL.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/orapwORCL': No such file or directory

Executing user defined scripts
/opt/oracle/runOracle.sh: running /opt/oracle/scripts/setup/01-install.sh
##### Install dependencies if required #####
##### Extracting files ####
##### Installing APEX #####
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
Installing APEX
/opt/oracle/scripts/setup/package/installApex.sh: line 13: sqlplus: command not found
##### Installing ORDS #####
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
May 20, 2019 2:46:19 PM  
INFO: Set config.dir to /opt/oracle/oradata/ordsconfig/PDB01 in: /opt/oracle/product/ords/ords.war
May 20, 2019 2:46:25 PM oracle.dbtools.rt.config.setup.SchemaSetup getInstallOrUpgrade
WARNING: Failed to connect to user ORDS_PUBLIC_USER jdbc:oracle:thin:@//localhost:1521/PDB01

**Comment by carldewever** [comment]
I started all over again.
The script is still not able to create the xe-directory, even not with sudo, even not with chmod 777.
However, if I create it myself while 02-run.sh is running right after the oradata directory is created, then everything goes as planned. The database is created etc etc
So this is a workaround for mac users that have the same problem

**Comment by carldewever** [comment]
my environment : mac osx 10.14.5

to resume, if I create the "xe" directory manually while the 02-run.sh script is running right after "oradata" is created, everything works as it should
Even the dbconfig and the ordsconfig directory are created correctly

**Comment by kridhick** [comment]
Hi @fuzziebrain,  I also have similar issue in my mac. 

rsk@Karthikeyans-MacBook-Air docker-apex-stack-master % sudo bash 02-run.sh das mysettings.env
Password:
##### Check if Docker network oracle_network #####
oracle_network
Error response from daemon: network with name oracle_network already exists
##### Removing any previous containers #####
Error: No such container: das
##### Changing file ownership. May require password to continue. #####
##### Creating container das #####
2ae6218e3e3210e7f82f48a60f7de8b59b7c558488ee48ce24418e184ea99046
##### Tailing logs. Ctrl-C to exit. #####
ORACLE PASSWORD FOR SYS AND SYSTEM: Oracle18
Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
Confirm the password:
Configuring Oracle Listener.
Listener configuration succeeded.
Configuring Oracle Database XE.
Enter SYS user password: 
*******
Enter SYSTEM user password: 
*********
Enter PDBADMIN User Password: 
********
Prepare for db operation
Cannot create directory "/opt/oracle/oradata/XE".
7% complete
Copying database files
29% complete
100% complete
[FATAL] Recovery Manager failed to restore datafiles. Refer logs for details.
7% complete
0% complete
Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.

Database configuration failed. Check logs under '/opt/oracle/cfgtoollogs/dbca'.
mkdir: cannot create directory '/opt/oracle/oradata/dbconfig': Permission denied
mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/spfileXE.ora': No such file or directory
mv: cannot move '/opt/oracle/product/18c/dbhomeXE/dbs/orapwXE' to '/opt/oracle/oradata/dbconfig/XE/': No such file or directory
mv: cannot move '/opt/oracle/product/18c/dbhomeXE/network/admin/listener.ora' to '/opt/oracle/oradata/dbconfig/XE/': No such file or directory
mv: cannot move '/opt/oracle/product/18c/dbhomeXE/network/admin/tnsnames.ora' to '/opt/oracle/oradata/dbconfig/XE/': No such file or directory
cp: cannot create regular file '/opt/oracle/oradata/dbconfig/XE/': No such file or directory
ln: failed to create symbolic link '/opt/oracle/product/18c/dbhomeXE/dbs/orapwXE': File exists
cp: cannot stat '/opt/oracle/oradata/dbconfig/XE/oratab': No such file or directory

Executing user defined scripts
/opt/oracle/runOracle.sh: running /opt/oracle/scripts/setup/01-install.sh
##### Install dependencies if required #####
##### Extracting files ####
unzip:  cannot find or open /tmp/files/apex_20.1.zip, /tmp/files/apex_20.1.zip.zip or /tmp/files/apex_20.1.zip.ZIP.
chown: cannot access '/opt/oracle/product/apex': No such file or directory
##### Installing APEX #####
The Oracle base remains unchanged with value /opt/oracle
Installing APEX
/opt/oracle/scripts/setup/package/installApex.sh: line 10: cd: /opt/oracle/product/apex: No such file or directory

SQL*Plus: Release 18.0.0.0.0 - Production on Sun Jun 21 05:56:13 2020
Version 18.4.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.


Connected to:
Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0

SQL> ERROR:
ORA-65011: Pluggable database XEPDB1 does not exist.


SQL> SQL> SQL> SP2-0310: unable to open file "apexins.sql"
SQL> SQL> SQL> SP2-0310: unable to open file "apex_rest_config_core.sql"
SQL> SQL> SQL>   alter user apex_public_user identified by "Oracle18_1" account unlock
*
ERROR at line 1:
ORA-01109: database not open


SQL> SQL> SQL> Setup Network ACL
SQL>   2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18        from sys.dba_registry
               *
ERROR at line 4:
ORA-06550: line 4, column 16:
PL/SQL: ORA-01219: database or pluggable database not open: queries allowed on
fixed tables or views only
ORA-06550: line 3, column 7:
PL/SQL: SQL Statement ignored
ORA-06550: line 9, column 18:
PLS-00201: identifier 'XS$ACE_TYPE' must be declared
ORA-06550: line 7, column 7:
PL/SQL: Statement ignored

**Comment by fuzziebrain** [comment]
@kridhick You shouldn't need to run the command with `sudo`. Can you please also let me know what the permissions are for the directory `das-oradata`?

**Comment by kridhick** [comment]
Hi @fuzziebrain, thank you for quick response. After providing necessary permisson to my das-oradata folder prior to running the docker (2nd step), I was able to get past DB installation and my database is up and running. Thank you so much. 

However, I had encountered a minor issue while installing the Apex. Kindly refer the highlighted/bold section. Shell unable to extract or find the apex_20_1.zip file, even though I had placed those in my files directory prior to running the script. Do I need to grant full permission there as well? Please suggest. 

Thank you so much for your work, its really helps. If you have Buy me coffee link, please let me know, I am happy support. 

Regards,
Karthikeyan

Log:
100% complete
Database creation complete. For details check the logfiles at:
 /opt/oracle/cfgtoollogs/dbca/XE.
Database Information:
Global Database Name:XE
System Identifier(SID):XE
Look at the log file "/opt/oracle/cfgtoollogs/dbca/XE/XE.log" for further details.

Connect to Oracle Database using one of the connect strings:
     Pluggable database: 27744138d70f/XEPDB1
     Multitenant container database: 27744138d70f
Use https://localhost:5500/em to access Oracle Enterprise Manager for Oracle Database XE

Executing user defined scripts
/opt/oracle/runOracle.sh: running /opt/oracle/scripts/setup/01-install.sh
##### Install dependencies if required #####
##### Extracting files ####
**unzip:  cannot find or open /tmp/files/apex_20.1.zip, /tmp/files/apex_20.1.zip.zip or /tmp/files/apex_20.1.zip.ZIP.
chown: cannot access '/opt/oracle/product/apex': No such file or directory**
##### Installing APEX #####
The Oracle base remains unchanged with value /opt/oracle
/opt/oracle/scripts/setup/package/installApex.sh: line 10: cd: /opt/oracle/product/apex: No such file or directory
Installing APEX

SQL*Plus: Release 18.0.0.0.0 - Production on Sun Jun 21 21:02:49 2020
Version 18.4.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.


Connected to:
Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0

SQL> 
Session altered.

SQL> SQL> SQL> SP2-0310: unable to open file "apexins.sql"
SQL> SQL> SQL> SP2-0310: unable to open file "apex_rest_config_core.sql"
SQL> SQL> SQL>   alter user apex_public_user identified by "Oracle18_1" account unlock
             *
ERROR at line 1:
ORA-01918: user 'APEX_PUBLIC_USER' does not exist


SQL> SQL> SQL> Setup Network ACL
SQL>   2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18  
PL/SQL procedure successfully completed.

SQL> SQL> SQL> Setup APEX Admin account
SQL>   2    3    4    5    6    7    8    9   10   11   12      apex_util.set_workspace(p_workspace => 'internal');
    *
ERROR at line 2:
ORA-06550: line 2, column 5:
PLS-00201: identifier 'APEX_UTIL.SET_WORKSPACE' must be declared
ORA-06550: line 2, column 5:
PL/SQL: Statement ignored
ORA-06550: line 3, column 5:
PLS-00201: identifier 'APEX_UTIL.CREATE_USER' must be declared
ORA-06550: line 3, column 5:
PL/SQL: Statement ignored


SQL> Disconnected from Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0
##### Installing ORDS #####
