### ISSUE TITLE
Enterprise manager URL not available

### ISSUE THREAD

**Issue by iorfmer** [fuzziebrain/docker-apex-stack#9]
Hi,

These are my settings regarding Enterprise Manager:

DOCKER_EM_PORT=55500
DB_VERSION=19.3.0
DB_EDITION=se2

Firewall rules por port 55500 has been established, but Enterprise Manager URL give me an ERR_CONNECTION_RESET error. Apex environment has been set up correctly.

Thanks.

**Comment by fuzziebrain** [comment]
@iorfmer Thanks for reporting this issue. Should be fixed now. Please let me know otherwise.

**Comment by iorfmer** [comment]
Hi,

I've executed:

sqlplus / as sysdba << EOF
  exec dbms_xdb_config.setlistenerlocalaccess(false);
  exec dbms_xdb_config.setglobalportenabled(true);
EOF

And still no access. It seems issue is related to version 19.3.0, maybe some databse setup changes, I'm investigating.

Thanks.

**Comment by iorfmer** [comment]
Sorry, I forgot to post a previous message.

I executed fixed script and still no EM access. Then I tried SQL command I found in the script, and still no access.

Many thanks for your quick fix.

**Comment by fuzziebrain** [comment]
Thanks for pointing out. This script was created for 18c XE, so I'll have to see how it impacts the other versions and editions. Will re-open this issue and let you know when I have a fix.

**Comment by fuzziebrain** [comment]
@iorfmer Unfortunately, I can't reproduce your issue on 19.3.0, in both SE2 and EE installs. I have EM Express running without any modifications to the scripts involve in configuring EM.

**Comment by iorfmer** [comment]
Thanks @fuzziebrain, did yo use port 55500 or 5500 for EM?

**Comment by fuzziebrain** [comment]
@iorfmer It shouldn't matter. Running either with ports 5500 and 55500 mapped worked for me. What's the link that you used?

**Comment by iorfmer** [comment]
Hi @fuzziebrain, 

I pointted to my servei ip using both ports. I've opened both ports as well and teste them with telnet successfully. I think the issue is on my own, something regarding server infrastructure, I will investigate deeper. Anyway, many thanks for your help. Your script save us a lot of time.

Regards.
